# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    - avoid_print: false
    - prefer_const_constructors: true
    - prefer_const_declarations: true
    - avoid_redundant_argument_values: true
    - prefer_single_quotes: true
